name: super-linter
on:
  push:
    branches: [main]
jobs:
  super-lint:
    name: lint code base
    runs-on : ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v3      
        
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: single line
        run: echo Hello,world!
      
      - name: list all the original file
        run: ls

      - name: install python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.8'
      
      - name: run script of python
        run: python file.py
        
      - name: list the updates files
        run: ls
      
        # install python
        # create a file
        # list the files again
      
